version: '3.7'

x-minio-common: &minio-common
  image: minio/minio
  command: server -address=":${MINIO_S3_PORT}" --console-address ":${MINIO_ADMIN_PORT}" /data1
  # Form multiple nodes:
  #  command: server --address ":${MINIO_S3_PORT}" --console-address ":${MINIO_ADMIN_PORT}" http://minio{1...4}/data{1...2}
  env_file:
    - .env
  ports:
    - ${NGINX_MINIO_S3_PORT}:${MINIO_S3_PORT}
    - ${NGINX_MINIO_ADMIN_PORT}:${MINIO_ADMIN_PORT}

services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    image: nginx:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".tpl"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/templates:/etc/nginx/templates
    links:
      - minio1
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    networks:
      default:
        aliases:
          - ${DOMAIN_MINIO_S3}
          - ${DOMAIN_MINIO_ADMIN}

  minio1:
    <<: *minio-common
    container_name: "${COMPOSE_PROJECT_NAME}_minio1"
    restart: unless-stopped
    hostname: minio1
    volumes:
      - ./docker/minio/data/data1-1:/data1
      # - ./data1-2:/data2
    networks:
      - default
    healthcheck:
      test: curl -f http://localhost:${MINIO_S3_PORT}/minio/health/live
      interval: 3s
      timeout: 3s
      retries: 10

  minio-create-buckets:
    profiles:
      - create-buckets
    image: minio/mc
    depends_on:
      minio1:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - default
    entrypoint: >
      sh -c "
        mc alias set ${MINIO_ALIAS} http://minio1:${MINIO_S3_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc rb --force --quiet ${MINIO_ALIAS}/${MINIO_BUCKET_NAME};
        mc mb ${MINIO_ALIAS}/${MINIO_BUCKET_NAME};
        mc anonymous set download ${MINIO_ALIAS}/${MINIO_BUCKET_NAME};
        exit 0;
      "

  #  minio2:
  #    <<: *minio-common
  #    hostname: minio2
  #    volumes:
  #      - data2-1:/data1
  #      - data2-2:/data2
  #
  #  minio3:
  #    <<: *minio-common
  #    hostname: minio3
  #    volumes:
  #      - data3-1:/data1
  #      - data3-2:/data2
  #
  #  minio4:
  #    <<: *minio-common
  #    hostname: minio4
  #    volumes:
  #      - data4-1:/data1
  #      - data4-2:/data2

networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}-network"
    external: true
